# otel-gateway-config.yaml
extensions:
  # 1. 인증 설정 (API Key 정의)
  bearertokenauth/incoming:
    token: "my-secret-api-key-1234"
  health_check:
    endpoint: "0.0.0.0:13133"

receivers:
  otlp:
    protocols:
      # grpc:
      #   endpoint: 0.0.0.0:4317
      #   auth:
      #     authenticator: bearertokenauth/incoming
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: bearertokenauth/incoming

processors:
  # 2. 메모리 보호 (급격한 트래픽 스파이크 방지)
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200

  # 3. 배치 처리 (네트워크 전송 효율화)
  batch:
    send_batch_size: 2000
    timeout: 5s

exporters:
  # OpenObserve로 보내는 설정
  otlphttp/openobserve:
    endpoint: "http://openobserve:5080/api/default" # Docker Service Name 사용
    headers:
      # admin@example.com : ChangeMe123! 의 Base64 인코딩 값
      # echo -n 'admin@example.com:ChangeMe123!' | base64
      Authorization: "Basic YWRtaW5AZXhhbXBsZS5jb206Q2hhbmdlTWUxMjMh"
      stream-name: "default"
    tls:
      insecure: true

service:
  extensions: [bearertokenauth/incoming, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/openobserve]